"""Initial

Revision ID: 99de1b48670d
Revises: 
Create Date: 2026-09-30 21:48:04.672794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99de1b48670d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('reminder_email', sa.String(), nullable=True),
    sa.Column('digest_enabled', sa.Boolean(), nullable=True),
    sa.Column('digest_time', sa.String(), nullable=True),
    sa.Column('quiet_start', sa.String(), nullable=True),
    sa.Column('quiet_end', sa.String(), nullable=True),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_table('works',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('recurrence_type', sa.String(), nullable=True),
    sa.Column('recurrence_config', sa.JSON(), nullable=True),
    sa.Column('time_of_day', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('reminder_offset_minutes', sa.Integer(), nullable=True),
    sa.Column('reminder_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_works_id'), 'works', ['id'], unique=False)
    op.create_index(op.f('ix_works_user_id'), 'works', ['user_id'], unique=False)
    op.create_table('reminder_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('work_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('provider_message_id', sa.String(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminder_jobs_id'), 'reminder_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_reminder_jobs_idempotency_key'), 'reminder_jobs', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_reminder_jobs_scheduled_for'), 'reminder_jobs', ['scheduled_for'], unique=False)
    op.create_table('subtasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('work_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subtasks_id'), 'subtasks', ['id'], unique=False)
    op.create_table('work_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('work_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('snoozed_until', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_logs_date'), 'work_logs', ['date'], unique=False)
    op.create_index(op.f('ix_work_logs_id'), 'work_logs', ['id'], unique=False)
    op.create_index(op.f('ix_work_logs_work_id'), 'work_logs', ['work_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_logs_work_id'), table_name='work_logs')
    op.drop_index(op.f('ix_work_logs_id'), table_name='work_logs')
    op.drop_index(op.f('ix_work_logs_date'), table_name='work_logs')
    op.drop_table('work_logs')
    op.drop_index(op.f('ix_subtasks_id'), table_name='subtasks')
    op.drop_table('subtasks')
    op.drop_index(op.f('ix_reminder_jobs_scheduled_for'), table_name='reminder_jobs')
    op.drop_index(op.f('ix_reminder_jobs_idempotency_key'), table_name='reminder_jobs')
    op.drop_index(op.f('ix_reminder_jobs_id'), table_name='reminder_jobs')
    op.drop_table('reminder_jobs')
    op.drop_index(op.f('ix_works_user_id'), table_name='works')
    op.drop_index(op.f('ix_works_id'), table_name='works')
    op.drop_table('works')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
